### **`Logistics and Last-Mile Delivery Data Quality Testing`**
---

###  **Objective**
To identify data quality issues in logistics data using Python and Pandas.

The test cases cover route sequences, proof of delivery, exception
reasons, delivery timestamps, missing events, invalid amounts,
parent shipments, customer privacy, and duplicate tracking IDs.

In [7]:
import pandas as pd

df=pd.read_csv('cleaned_logistics_checkpoint.csv')

df

,Shipment_ID,Parent_Shipment_ID,Order_Status,Tracking_ID,Parcel_ID,Parcel_Count,Carrier,Service_Level,Scan_Source,Event_TS,...,Exception_Reason,Declared_Value,Freight_Cost,Surcharge,COD_Amount,Claim_Amount,Currency,Customer_Name,Customer_Phone,Street_Address
0,SHP-10001,NaN,ACTIVE,trk-9001,PCL-9001,1,FastShip,Exp,DRIVER_APP,2026-07-12 09:00 +05:30,...,NaN,2500.00,120.00,15.0,500.0000,0,INR,Ramesh Mohanty,+91-9861012345,"Plot 42, Saheed Nagar, Bhubaneswar"
1,SHP-10001,NaN,ACTIVE,TRK-9001,PCL-9001,1,FAST SHIP,EXPRESS,HUB_SCANNER,2026-07-12T03:30:00Z,...,NaN,2500.00,120.00,15.0,500.0000,0,INR,Ramesh Mohanty,9861012345,"Plot 42, Saheed Nagar, Bhubaneswar"
2,SHP-10002,NaN,ACTIVE,TRK-9002,PCL-9002,1,RoadX,Std,DRIVER_APP,2026-07-13 08:00,...,NaN,1800.00,0.00,0.0,0.0000,0,INR,Sujata Das,9437054321,"Link Road, Near Nishamani Hall, Cuttack"
3,SHP-10003,NaN,ACTIVE,TRK-9003,PCL-9003,2,Road-X,STANDARD,HUB_SCANNER,2026-07-13T10:00:00Z,...,Damaged,1200.00,210.00,25.0,1200.0000,1200,INR,Bikash Jena,8249011223,"Buxi Bazar, Main Road, Cuttack"
4,SHP-10004,SHP-09950,RETURN_RTS,TRK-9002,PCL-9004,1,Fast-Ship,EXPRESS,DRIVER_APP,2026-07-11T04:00:00Z,...,Recipient Unavailable,3200.00,150.00,0.0,0.0000,0,INR,Anita Patra,7008122334,"Kalpana Square, Laxmisagar, BBSR"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,SHP-11915,NaN,ACTIVE,TRK-11915,PCL-11915,1,Odisha-Exp,Next-Day,API_WEBHOOK,2026-07-10 10:54 +05:30,...,NaN,8531.66,209.81,25.0,450.0000,0,INR,Manas Bhoi,07110896587,"Plot 42, Saheed Nagar, Bhubaneswar"
9996,SHP-11915,NaN,ACTIVE,TRK-11915,PCL-11915,1,FastShip,Next-Day,HUB_SCANNER,2026-07-10T12:51:00Z,...,NaN,8531.66,209.81,25.0,450.0000,0,NaN,Manas Bhoi,07110896587,"Plot 42, Saheed Nagar, Bhubaneswar"
9997,SHP-11915,NaN,ACTIVE,TRK-11915,PCL-11915,1,Odisha-Exp,Next-Day,DRIVER_APP,2026-07-11 00:04 +05:30,...,NaN,8531.66,0.00,25.0,0.4500,0,INR,Manas Bhoi,07110896587,"Plot 42, Saheed Nagar, Bhubaneswar"
9998,TEST-11916,NaN,TEST_ORDER,TRK-11916,PCL-11916,0,OdishaExpress,EXPRESS,DRIVER_APP,2026-07-23 10:43 +05:30,...,NaN,4732.47,0.00,50.0,2499.0000,0,INR,NaN,9069150103,"Fakir Mohan Golai, Station Road, Balasore"
9999,TEST-11916,NaN,TEST_ORDER,TRK-11916,PCL-11916,0,OdishaExpress,EXPRESS,MANUAL_ENTRY,2026-07-24 00:09 +05:30,...,NaN,4732.47,0.00,50.0,0.2499,0,INR,NaN,9069150103,"Fakir Mohan Golai, Station Road, Balasore"

In [4]:
print('Display Shape',df.shape) # Display the dataset size

print(df.columns.tolist)        # Display column names

df.head()                       # Display the first five rows

Display Shape (10000, 35)
<bound method IndexOpsMixin.tolist of Index(['Shipment_ID', 'Parent_Shipment_ID', 'Order_Status', 'Tracking_ID',
       'Parcel_ID', 'Parcel_Count', 'Carrier', 'Service_Level', 'Scan_Source',
       'Event_TS', 'Promised_Delivery_TS', 'Event_Code', 'Status',
       'Origin_Depot', 'Destination_Zone', 'Country_Code', 'Route_ID',
       'Stop_Seq', 'GPS_Coords', 'Weight', 'Weight_Unit', 'Dimensions_L_W_H',
       'Dim_Unit', 'Attempt_No', 'POD_ID', 'Exception_Reason',
       'Declared_Value', 'Freight_Cost', 'Surcharge', 'COD_Amount',
       'Claim_Amount', 'Currency', 'Customer_Name', 'Customer_Phone',
       'Street_Address'],
      dtype='object')>

,Shipment_ID,Parent_Shipment_ID,Order_Status,Tracking_ID,Parcel_ID,Parcel_Count,Carrier,Service_Level,Scan_Source,Event_TS,...,Exception_Reason,Declared_Value,Freight_Cost,Surcharge,COD_Amount,Claim_Amount,Currency,Customer_Name,Customer_Phone,Street_Address
0,SHP-10001,NaN,ACTIVE,trk-9001,PCL-9001,1,FastShip,Exp,DRIVER_APP,2026-07-12 09:00 +05:30,...,NaN,2500.0,120.0,15.0,500.0,0,INR,Ramesh Mohanty,+91-9861012345,"Plot 42, Saheed Nagar, Bhubaneswar"
1,SHP-10001,NaN,ACTIVE,TRK-9001,PCL-9001,1,FAST SHIP,EXPRESS,HUB_SCANNER,2026-07-12T03:30:00Z,...,NaN,2500.0,120.0,15.0,500.0,0,INR,Ramesh Mohanty,9861012345,"Plot 42, Saheed Nagar, Bhubaneswar"
2,SHP-10002,NaN,ACTIVE,TRK-9002,PCL-9002,1,RoadX,Std,DRIVER_APP,2026-07-13 08:00,...,NaN,1800.0,0.0,0.0,0.0,0,INR,Sujata Das,9437054321,"Link Road, Near Nishamani Hall, Cuttack"
3,SHP-10003,NaN,ACTIVE,TRK-9003,PCL-9003,2,Road-X,STANDARD,HUB_SCANNER,2026-07-13T10:00:00Z,...,Damaged,1200.0,210.0,25.0,1200.0,1200,INR,Bikash Jena,8249011223,"Buxi Bazar, Main Road, Cuttack"
4,SHP-10004,SHP-09950,RETURN_RTS,TRK-9002,PCL-9004,1,Fast-Ship,EXPRESS,DRIVER_APP,2026-07-11T04:00:00Z,...,Recipient Unavailable,3200.0,150.0,0.0,0.0,0,INR,Anita Patra,7008122334,"Kalpana Square, Laxmisagar, BBSR"

### **`Test Case 11: Proof-of-Delivery Validation`**
---

#### **Objective :-**
`Check whether delivery records have a shipment ID, POD ID,
and a valid delivery attempt number.`

#### **Expected Result :-**
`Identify delivery records with missing POD information
or invalid shipment and attempt details.`