In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("cleaned_logistics_checkpoint.csv")
print(df)

     Shipment_ID Parent_Shipment_ID Order_Status Tracking_ID  Parcel_ID  \
0      SHP-10001                NaN       ACTIVE   trk-9001    PCL-9001
1      SHP-10001                NaN       ACTIVE    TRK-9001   PCL-9001
2      SHP-10002                NaN       ACTIVE    TRK-9002   PCL-9002
3      SHP-10003                NaN       ACTIVE    TRK-9003   PCL-9003
4      SHP-10004          SHP-09950   RETURN_RTS    TRK-9002   PCL-9004
...          ...                ...          ...         ...        ...
9995   SHP-11915                NaN       ACTIVE   TRK-11915  PCL-11915
9996   SHP-11915                NaN       ACTIVE   TRK-11915  PCL-11915
9997   SHP-11915                NaN       ACTIVE   TRK-11915  PCL-11915
9998  TEST-11916                NaN   TEST_ORDER   TRK-11916  PCL-11916
9999  TEST-11916                NaN   TEST_ORDER   TRK-11916  PCL-11916

      Parcel_Count        Carrier Service_Level   Scan_Source  \
0                1       FastShip           Exp    DRIVER_APP
1                1      FAST SHIP       EXPRESS   HUB_SCANNER
2                1          RoadX           Std    DRIVER_APP
3                2         Road-X      STANDARD   HUB_SCANNER
4                1      Fast-Ship       EXPRESS    DRIVER_APP
...            ...            ...           ...           ...
9995             1     Odisha-Exp      Next-Day   API_WEBHOOK
9996             1       FastShip      Next-Day   HUB_SCANNER
9997             1     Odisha-Exp      Next-Day    DRIVER_APP
9998             0  OdishaExpress       EXPRESS    DRIVER_APP
9999             0  OdishaExpress       EXPRESS  MANUAL_ENTRY

                     Event_TS  ...       Exception_Reason Declared_Value  \
0     2026-07-12 09:00 +05:30  ...                    NaN        2500.00
1        2026-07-12T03:30:00Z  ...                    NaN        2500.00
2            2026-07-13 08:00  ...                    NaN        1800.00
3        2026-07-13T10:00:00Z  ...                Damaged        1200.00
4        2026-07-11T04:00:00Z  ...  Recipient Unavailable        3200.00
...                       ...  ...                    ...            ...
9995  2026-07-10 10:54 +05:30  ...                    NaN        8531.66
9996     2026-07-10T12:51:00Z  ...                    NaN        8531.66
9997  2026-07-11 00:04 +05:30  ...                    NaN        8531.66
9998  2026-07-23 10:43 +05:30  ...                    NaN        4732.47
9999  2026-07-24 00:09 +05:30  ...                    NaN        4732.47

     Freight_Cost Surcharge COD_Amount Claim_Amount Currency   Customer_Name  \
0          120.00      15.0   500.0000            0      INR  Ramesh Mohanty
1          120.00      15.0   500.0000            0      INR  Ramesh Mohanty
2            0.00       0.0     0.0000            0      INR      Sujata Das
3          210.00      25.0  1200.0000         1200      INR     Bikash Jena
4          150.00       0.0     0.0000            0      INR     Anita Patra
...           ...       ...        ...          ...      ...             ...
9995       209.81      25.0   450.0000            0      INR      Manas Bhoi
9996       209.81      25.0   450.0000            0      NaN      Manas Bhoi
9997         0.00      25.0     0.4500            0      INR      Manas Bhoi
9998         0.00      50.0  2499.0000            0      INR             NaN
9999         0.00      50.0     0.2499            0      INR             NaN

      Customer_Phone                             Street_Address
0     +91-9861012345         Plot 42, Saheed Nagar, Bhubaneswar
1         9861012345         Plot 42, Saheed Nagar, Bhubaneswar
2         9437054321    Link Road, Near Nishamani Hall, Cuttack
3         8249011223             Buxi Bazar, Main Road, Cuttack
4         7008122334           Kalpana Square, Laxmisagar, BBSR
...              ...                                        ...
9995     07110896587         Plot 42, Saheed Nagar, Bhubaneswar
9996     07110896587         Plot 42, Saheed Nagar, Bhubaneswar
9997     07110896587         Plot 42, Saheed Nagar, Bhubaneswar
9998      9069150103  Fakir Mohan Golai, Station Road, Balasore
9999      9069150103  Fakir Mohan Golai, Station Road, Balasore

[10000 rows x 35 columns]

For testcase-01

In [4]:
print(df.columns)

Index(['Shipment_ID', 'Parent_Shipment_ID', 'Order_Status', 'Tracking_ID',
       'Parcel_ID', 'Parcel_Count', 'Carrier', 'Service_Level', 'Scan_Source',
       'Event_TS', 'Promised_Delivery_TS', 'Event_Code', 'Status',
       'Origin_Depot', 'Destination_Zone', 'Country_Code', 'Route_ID',
       'Stop_Seq', 'GPS_Coords', 'Weight', 'Weight_Unit', 'Dimensions_L_W_H',
       'Dim_Unit', 'Attempt_No', 'POD_ID', 'Exception_Reason',
       'Declared_Value', 'Freight_Cost', 'Surcharge', 'COD_Amount',
       'Claim_Amount', 'Currency', 'Customer_Name', 'Customer_Phone',
       'Street_Address'],
      dtype='str')

In [5]:
print(df["Tracking_ID"].head(10))

0      trk-9001
1       TRK-9001
2       TRK-9002
3       TRK-9003
4       TRK-9002
5      TRK-10005
6    TRK-10005
7      TRK-10005
8      TRK-10005
9      TRK-10005
Name: Tracking_ID, dtype: str

In [6]:

df["Tracking_ID"] = df["Tracking_ID"].str.strip()
df["Tracking_ID"] = df["Tracking_ID"].str.upper()

print(df["Tracking_ID"].head())

df.to_csv("TC01_Output.csv", index=False)

0    TRK-9001
1    TRK-9001
2    TRK-9002
3    TRK-9003
4    TRK-9002
Name: Tracking_ID, dtype: str

For testcase-02

In [7]:
df[df["Tracking_ID"].str.upper()=="TRK-9001"]

,Shipment_ID,Parent_Shipment_ID,Order_Status,Tracking_ID,Parcel_ID,Parcel_Count,Carrier,Service_Level,Scan_Source,Event_TS,...,Exception_Reason,Declared_Value,Freight_Cost,Surcharge,COD_Amount,Claim_Amount,Currency,Customer_Name,Customer_Phone,Street_Address
0,SHP-10001,NaN,ACTIVE,TRK-9001,PCL-9001,1,FastShip,Exp,DRIVER_APP,2026-07-12 09:00 +05:30,...,NaN,2500.0,120.0,15.0,500.0,0,INR,Ramesh Mohanty,+91-9861012345,"Plot 42, Saheed Nagar, Bhubaneswar"
1,SHP-10001,NaN,ACTIVE,TRK-9001,PCL-9001,1,FAST SHIP,EXPRESS,HUB_SCANNER,2026-07-12T03:30:00Z,...,NaN,2500.0,120.0,15.0,500.0,0,INR,Ramesh Mohanty,9861012345,"Plot 42, Saheed Nagar, Bhubaneswar"

In [8]:
event_map = {
    "Pickup":"PICKED_UP",
    "PICKUP":"PICKED_UP",
    "picked_up":"PICKED_UP",
    "Picked Up":"PICKED_UP",
    "PICKED_UP":"PICKED_UP"
}

df["Event_TS"] = df["Event_TS"].replace(event_map)
print(df)

     Shipment_ID Parent_Shipment_ID Order_Status Tracking_ID  Parcel_ID  \
0      SHP-10001                NaN       ACTIVE    TRK-9001   PCL-9001
1      SHP-10001                NaN       ACTIVE    TRK-9001   PCL-9001
2      SHP-10002                NaN       ACTIVE    TRK-9002   PCL-9002
3      SHP-10003                NaN       ACTIVE    TRK-9003   PCL-9003
4      SHP-10004          SHP-09950   RETURN_RTS    TRK-9002   PCL-9004
...          ...                ...          ...         ...        ...
9995   SHP-11915                NaN       ACTIVE   TRK-11915  PCL-11915
9996   SHP-11915                NaN       ACTIVE   TRK-11915  PCL-11915
9997   SHP-11915                NaN       ACTIVE   TRK-11915  PCL-11915
9998  TEST-11916                NaN   TEST_ORDER   TRK-11916  PCL-11916
9999  TEST-11916                NaN   TEST_ORDER   TRK-11916  PCL-11916

      Parcel_Count        Carrier Service_Level   Scan_Source  \
0                1       FastShip           Exp    DRIVER_APP
1                1      FAST SHIP       EXPRESS   HUB_SCANNER
2                1          RoadX           Std    DRIVER_APP
3                2         Road-X      STANDARD   HUB_SCANNER
4                1      Fast-Ship       EXPRESS    DRIVER_APP
...            ...            ...           ...           ...
9995             1     Odisha-Exp      Next-Day   API_WEBHOOK
9996             1       FastShip      Next-Day   HUB_SCANNER
9997             1     Odisha-Exp      Next-Day    DRIVER_APP
9998             0  OdishaExpress       EXPRESS    DRIVER_APP
9999             0  OdishaExpress       EXPRESS  MANUAL_ENTRY

                     Event_TS  ...       Exception_Reason Declared_Value  \
0     2026-07-12 09:00 +05:30  ...                    NaN        2500.00
1        2026-07-12T03:30:00Z  ...                    NaN        2500.00
2            2026-07-13 08:00  ...                    NaN        1800.00
3        2026-07-13T10:00:00Z  ...                Damaged        1200.00
4        2026-07-11T04:00:00Z  ...  Recipient Unavailable        3200.00
...                       ...  ...                    ...            ...
9995  2026-07-10 10:54 +05:30  ...                    NaN        8531.66
9996     2026-07-10T12:51:00Z  ...                    NaN        8531.66
9997  2026-07-11 00:04 +05:30  ...                    NaN        8531.66
9998  2026-07-23 10:43 +05:30  ...                    NaN        4732.47
9999  2026-07-24 00:09 +05:30  ...                    NaN        4732.47

     Freight_Cost Surcharge COD_Amount Claim_Amount Currency   Customer_Name  \
0          120.00      15.0   500.0000            0      INR  Ramesh Mohanty
1          120.00      15.0   500.0000            0      INR  Ramesh Mohanty
2            0.00       0.0     0.0000            0      INR      Sujata Das
3          210.00      25.0  1200.0000         1200      INR     Bikash Jena
4          150.00       0.0     0.0000            0      INR     Anita Patra
...           ...       ...        ...          ...      ...             ...
9995       209.81      25.0   450.0000            0      INR      Manas Bhoi
9996       209.81      25.0   450.0000            0      NaN      Manas Bhoi
9997         0.00      25.0     0.4500            0      INR      Manas Bhoi
9998         0.00      50.0  2499.0000            0      INR             NaN
9999         0.00      50.0     0.2499            0      INR             NaN

      Customer_Phone                             Street_Address
0     +91-9861012345         Plot 42, Saheed Nagar, Bhubaneswar
1         9861012345         Plot 42, Saheed Nagar, Bhubaneswar
2         9437054321    Link Road, Near Nishamani Hall, Cuttack
3         8249011223             Buxi Bazar, Main Road, Cuttack
4         7008122334           Kalpana Square, Laxmisagar, BBSR
...              ...                                        ...
9995     07110896587         Plot 42, Saheed Nagar, Bhubaneswar
9996     07110896587         Plot 42, Saheed Nagar, Bhubaneswar
9997     07110896587         Plot 42, Saheed Nagar, Bhubaneswar
9998      9069150103  Fakir Mohan Golai, Station Road, Balasore
9999      9069150103  Fakir Mohan Golai, Station Road, Balasore

[10000 rows x 35 columns]

In [9]:
def convert_weight(weight, unit):
    if unit.lower() == "g":
        return weight / 1000
    elif unit.lower() == "kg":
        return weight

In [10]:
df["Weight_kg"] = df.apply(
    lambda x: convert_weight(x["Weight"], x["Weight_Unit"]),
    axis=1
)

In [11]:
print(df["Weight_Unit"].unique())

<StringArray>
['g', 'kg', 'lb']
Length: 3, dtype: str

In [12]:
carrier_map = {
    "FastShip":"FASTSHIP",
    "FAST SHIP":"FASTSHIP",
    "Road-X":"ROADX",
    "RoadX":"ROADX"
}

df["Carrier"] = df["Carrier"].replace(carrier_map)

In [13]:
print(df["Carrier"].unique())

<StringArray>
[       'FASTSHIP',           'ROADX',       'Fast-Ship',        'BLUE JET',
         'BlueJet',          'ROAD_X',  'ODISHA EXPRESS',        'Blue-Jet',
      'Odisha-Exp',   'OdishaExpress', 'roadx_logistics',    'fastship_exp']
Length: 12, dtype: str

In [14]:
event_map = {
    "Pickup": "PICKED_UP",
    "Picked Up": "PICKED_UP",
    "picked_up": "PICKED_UP",
    "PICKUP": "PICKED_UP",
    "PICKED_UP": "PICKED_UP"
}

df["Event_Code"] = df["Event_Code"].replace(event_map)

In [15]:
print(df["Event_Code"].unique())

<StringArray>
[       'PICKED_UP',        'Delivered',        'DELIVERED',
          'Created',   'Arrived_At_Hub', 'out_for_delivery',
        'EXCEPTION',         'Returned',  'Label_Generated',
       'In Transit', 'Out_For_Delivery',    'ORDER_CREATED',
       'in_transit', 'Out for Delivery',    'Deliv_Success',
       'IN_TRANSIT',  'Delivery_Failed',              'OFD',
             'Hold',        'Exception',        'delivered',
          'created',              'RTS', 'Return_To_Sender',
         'returned']
Length: 25, dtype: str

In [16]:
def convert_weight(weight, unit):
    unit = str(unit).lower()

    if unit == "g":
        return weight / 1000

    elif unit == "kg":
        return weight

    else:
        return None

In [17]:
df["Weight_kg"] = df.apply(
    lambda x: convert_weight(x["Weight"], x["Weight_Unit"]),
    axis=1
)

In [18]:
print(df[["Weight","Weight_Unit","Weight_kg"]].head())

   Weight Weight_Unit  Weight_kg
0  1500.0           g        1.5
1     1.5          kg        1.5
2     2.2          kg        2.2
3    -4.0          kg       -4.0
4     4.4          lb        NaN

In [19]:
df["Event_TS"] = pd.to_datetime(
    df["Event_TS"],
    format="mixed",
    utc=True,
    errors="coerce"
)

In [20]:
print(df["Event_TS"].isna().sum())

175

In [21]:
df[df["Event_TS"].isna()]

,Shipment_ID,Parent_Shipment_ID,Order_Status,Tracking_ID,Parcel_ID,Parcel_Count,Carrier,Service_Level,Scan_Source,Event_TS,...,Declared_Value,Freight_Cost,Surcharge,COD_Amount,Claim_Amount,Currency,Customer_Name,Customer_Phone,Street_Address,Weight_kg
7,SHP-10005,NaN,ACTIVE,TRK-10005,PCL-10005,1,BLUE JET,standard,HUB_SCANNER,NaT,...,2972.83,0.00,50.0,0.00,0,INR,Manas Patnaik,+91-9581769315,NaN,24.26
83,SHP-10019,NaN,ACTIVE,TRK-10019,PCL-10019,1,FASTSHIP,express,DRIVER_APP,NaT,...,-500.00,354.40,50.0,0.00,0,INR,gayatri Patnaik,+91-9645637350,"Link Road, Near Nishamani Hall, Cuttack",19.70
97,shp-10022,NaN,ACTIVE,TRK-10022,PCL-10022,1,fastship_exp,standard,API_WEBHOOK,NaT,...,6136.12,84.84,0.0,0.00,0,INR,Rajesh Patnaik,+91-8455395417,"Flat 302, Patia Info City Road, Bhubaneswar",13.06
146,SHP-10031,NaN,ACTIVE,TRK-10031,PCL-10031,1,ROADX,EXPRESS,HUB_SCANNER,NaT,...,7673.16,440.47,25.0,1500.00,0,INR,Ipsita Lenka,7991255513,"VIP Road, Chakratirtha, Puri",6.53
173,SHP-10037,NaN,ACTIVE,TRK-10037,PCL-10037,1,Fast-Ship,Next-Day,API_WEBHOOK,NaT,...,3169.40,0.00,15.0,0.00,0,INR,Rashmi Tripathy,7862304797,"Gandhi Nagar 4th Lane, Berhampur",22.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9719,SHP-11861,NaN,ACTIVE,TRK-11861,PCL-11861,1,BlueJet,Exp,DRIVER_APP,NaT,...,-500.00,445.22,25.0,450.00,0,INR,Aarav Kar,+91-9474276361,"Charampa Station Bazar, Bhadrak",NaN
9817,shp-11880,SHP-11857,RETURN_RTS,TRK-11880,PCL-11880,1,ROAD_X,Next-Day,HUB_SCANNER,NaT,...,6636.68,0.00,50.0,0.45,0,INR,Sujata Das,+91-9785302292,"Kalpana Square, Laxmisagar, BBSR",5.26
9843,shp-11885,NaN,ACTIVE,TRK-11885,PCL-11885,1,ROADX,STANDARD,MANUAL_ENTRY,NaT,...,14578.10,106.94,50.0,0.00,0,INR,Aarav Mallick,7557674875,"Budharaja Main Road, Ainthapali, Sambalpur",23.82
9971,SHP-11910,NaN,ACTIVE,TRK-11910,PCL-11910,1,Fast-Ship,express,DRIVER_APP,NaT,...,4474.95,209.47,15.0,899.00,0,inr,Deepak Kar,NaN,"Gandhi Nagar 4th Lane, Berhampur",-22.26
9992,SHP-11914,NaN,ACTIVE,TRK-11914,PCL-11914,1,OdishaExpress,standard,MANUAL_ENTRY,NaT,...,2923.53,0.00,NaN,0.00,0,inr,Kishore Senapati,09426213453,"Kacheri Road, Near Collectorate, Bhadrak",0.56

In [22]:
df["Event_TS"] = df["Event_TS"].dt.strftime("%Y-%m-%dT%H:%M:%SZ")

In [23]:
print(df["Event_TS"].head())

0    2026-07-12T03:30:00Z
1    2026-07-12T03:30:00Z
2    2026-07-13T08:00:00Z
3    2026-07-13T10:00:00Z
4    2026-07-11T04:00:00Z
Name: Event_TS, dtype: str

In [24]:
df["Event_Key"] = (
    df["Tracking_ID"] + "_" +
    df["Event_Code"] + "_" +
    df["Event_TS"]
)

In [25]:
print(df["Event_Key"].head())

0    TRK-9001_PICKED_UP_2026-07-12T03:30:00Z
1    TRK-9001_PICKED_UP_2026-07-12T03:30:00Z
2    TRK-9002_Delivered_2026-07-13T08:00:00Z
3    TRK-9003_PICKED_UP_2026-07-13T10:00:00Z
4    TRK-9002_DELIVERED_2026-07-11T04:00:00Z
Name: Event_Key, dtype: str

In [26]:
df = df.drop_duplicates(subset="Event_Key", keep="first")

In [27]:
df[df["Tracking_ID"]=="TRK-9001"]

,Shipment_ID,Parent_Shipment_ID,Order_Status,Tracking_ID,Parcel_ID,Parcel_Count,Carrier,Service_Level,Scan_Source,Event_TS,...,Freight_Cost,Surcharge,COD_Amount,Claim_Amount,Currency,Customer_Name,Customer_Phone,Street_Address,Weight_kg,Event_Key
0,SHP-10001,NaN,ACTIVE,TRK-9001,PCL-9001,1,FASTSHIP,Exp,DRIVER_APP,2026-07-12T03:30:00Z,...,120.0,15.0,500.0,0,INR,Ramesh Mohanty,+91-9861012345,"Plot 42, Saheed Nagar, Bhubaneswar",1.5,TRK-9001_PICKED_UP_2026-07-12T03:30:00Z

In [28]:
df.to_csv("TC02_Output.csv", index=False)

For testcase-03

In [29]:
print(df["Event_TS"].head(10))

0     2026-07-12T03:30:00Z
2     2026-07-13T08:00:00Z
3     2026-07-13T10:00:00Z
4     2026-07-11T04:00:00Z
5     2026-07-23T09:15:00Z
6     2026-07-23T12:25:00Z
7                      NaN
8     2026-07-23T19:35:00Z
9     2026-07-24T03:07:00Z
10    2026-07-24T19:43:00Z
Name: Event_TS, dtype: str

In [30]:
df["Event_TS_UTC"] = pd.to_datetime(
    df["Event_TS"],
    format="mixed",
    utc=True,
    errors="coerce"
)

In [31]:
print(df["Event_TS_UTC"].isna().sum())

1

In [32]:
invalid_rows = df[df["Event_TS_UTC"].isna()]

print(invalid_rows[["Tracking_ID","Event_TS"]])

  Tracking_ID Event_TS
7   TRK-10005      NaN

In [33]:
df["Event_TS_UTC"] = df["Event_TS_UTC"].dt.strftime("%Y-%m-%dT%H:%M:%SZ")

In [34]:
print(df[["Tracking_ID","Event_TS","Event_TS_UTC"]].head(10))

   Tracking_ID              Event_TS          Event_TS_UTC
0     TRK-9001  2026-07-12T03:30:00Z  2026-07-12T03:30:00Z
2     TRK-9002  2026-07-13T08:00:00Z  2026-07-13T08:00:00Z
3     TRK-9003  2026-07-13T10:00:00Z  2026-07-13T10:00:00Z
4     TRK-9002  2026-07-11T04:00:00Z  2026-07-11T04:00:00Z
5    TRK-10005  2026-07-23T09:15:00Z  2026-07-23T09:15:00Z
6    TRK-10005  2026-07-23T12:25:00Z  2026-07-23T12:25:00Z
7    TRK-10005                   NaN                   NaN
8    TRK-10005  2026-07-23T19:35:00Z  2026-07-23T19:35:00Z
9    TRK-10005  2026-07-24T03:07:00Z  2026-07-24T03:07:00Z
10   TRK-10005  2026-07-24T19:43:00Z  2026-07-24T19:43:00Z

In [35]:
df.to_csv("TC03_Output.csv", index=False)

For testcase-04

In [36]:
df["Timezone_Status"] = "VALID"

In [37]:
mask = ~df["Event_TS"].astype(str).str.contains(r'Z|[+-]\d{2}:\d{2}', regex=True, na=False)

In [38]:
df.loc[mask, "Timezone_Status"] = "REVIEW"

In [39]:
print(df[df["Timezone_Status"] == "REVIEW"][["Tracking_ID", "Event_TS", "Timezone_Status"]])

  Tracking_ID Event_TS Timezone_Status
7   TRK-10005      NaN          REVIEW

In [40]:
print("Records needing review:", mask.sum())

Records needing review: 1

In [41]:
df.to_csv("TC04_Output.csv", index=False)

For testcase-05

In [42]:
print(df[["Tracking_ID", "Weight", "Weight_Unit"]].head(10))

   Tracking_ID    Weight Weight_Unit
0     TRK-9001   1500.00           g
2     TRK-9002      2.20          kg
3     TRK-9003     -4.00          kg
4     TRK-9002      4.40          lb
5    TRK-10005  24260.00           g
6    TRK-10005     24.26          kg
7    TRK-10005  24260.00           g
8    TRK-10005     24.26          kg
9    TRK-10005  24260.00           g
10   TRK-10005     53.48          lb

In [43]:
def convert_weight(weight, unit):
    unit = str(unit).lower()

    if unit == "g":
        return weight / 1000

    elif unit == "kg":
        return weight

    else:
        return None

In [44]:
df["Weight_kg"] = df.apply(
    lambda x: convert_weight(x["Weight"], x["Weight_Unit"]),
    axis=1
)

In [45]:
df["Weight_Status"] = "VALID"

In [46]:
df.loc[df["Weight_kg"] < 0, "Weight_Status"] = "REVIEW"

In [47]:
print(df[df["Weight_Status"] == "REVIEW"]
      [["Tracking_ID", "Weight", "Weight_kg", "Weight_Status"]])

     Tracking_ID    Weight  Weight_kg Weight_Status
3       TRK-9003     -4.00      -4.00        REVIEW
12     TRK-10006    -21.53     -21.53        REVIEW
31     TRK-10009     -9.03      -9.03        REVIEW
135    TRK-10020    -13.76     -13.76        REVIEW
137    TRK-10020 -13760.00     -13.76        REVIEW
...          ...       ...        ...           ...
9877   TRK-11891    -19.90     -19.90        REVIEW
9901   TRK-11896     -5.44      -5.44        REVIEW
9933   TRK-11902  -7600.00      -7.60        REVIEW
9941   TRK-11904     -2.12      -2.12        REVIEW
9968   TRK-11910    -22.26     -22.26        REVIEW

[194 rows x 4 columns]

In [48]:
print("Negative weight records:", (df["Weight_kg"] < 0).sum())

Negative weight records: 194

In [49]:
print(df["Weight"].dtype)

print(df["Weight"].head(10))

print(df["Weight"].min())

print(df[df["Weight"] < 0][["Tracking_ID","Weight","Weight_Unit"]].head(20))

float64
0      1500.00
2         2.20
3        -4.00
4         4.40
5     24260.00
6        24.26
7     24260.00
8        24.26
9     24260.00
10       53.48
Name: Weight, dtype: float64
-23730.0
    Tracking_ID    Weight Weight_Unit
3      TRK-9003     -4.00          kg
12    TRK-10006    -21.53          kg
31    TRK-10009     -9.03          kg
135   TRK-10020    -13.76          kg
137   TRK-10020 -13760.00           g
140   TRK-10030     -9.88          kg
144   TRK-10031     -6.53          kg
163   TRK-10035  -9120.00           g
164   TRK-10035     -9.12          kg
180   TRK-10038    -18.39          kg
182   TRK-10038 -18390.00           g
192   TRK-10037    -18.46          kg
238   TRK-10049    -20.66          kg
307   TRK-10063  -6170.00           g
345   TRK-10070    -15.33          kg
455   TRK-10091     -2.21          kg
458   TRK-10092    -33.16          lb
459   TRK-10092    -15.04          kg
472   TRK-10094    -18.21          kg
676   TRK-10133     -6.26          kg

In [50]:
valid_weight_df = df[df["Weight_Status"] == "VALID"]

In [51]:
print(valid_weight_df[["Tracking_ID", "Weight_kg"]].head())

  Tracking_ID  Weight_kg
0    TRK-9001       1.50
2    TRK-9002       2.20
4    TRK-9002        NaN
5   TRK-10005      24.26
6   TRK-10005      24.26

In [52]:


valid_weight_df.to_csv("TC05_Cleaned_Output.csv", index=False)

In [53]:
df[df["Weight_Status"] == "REVIEW"].to_csv(
    "TC05_Exception_Output.csv",
    index=False
)

For testcase-06

In [54]:
df["GPS_Coords"].head(10)

0        20.2961, 85.8245
2        20.4625, 85.8830
3     125.0000, -220.0000
4        20.2700, 85.8400
5        21.0514, 86.4668
6        21.0596, 86.5235
7        21.0353, 86.5176
8         21.082, 86.4943
9     115.6702, -233.9471
10        21.0649, 86.496
Name: GPS_Coords, dtype: str

In [55]:
df[['Latitude','Longitude']] = df['GPS_Coords'].str.split(',', expand=True)

In [56]:
df['Latitude'] = pd.to_numeric(df['Latitude'], errors='coerce')
df['Longitude'] = pd.to_numeric(df['Longitude'], errors='coerce')

In [57]:
invalid_gps = df[
    (df['Latitude'] < -90) |
    (df['Latitude'] > 90) |
    (df['Longitude'] < -180) |
    (df['Longitude'] > 180)
]

In [58]:
print("Invalid GPS Records:", len(invalid_gps))

Invalid GPS Records: 370

In [59]:
invalid_gps[['Tracking_ID',
             'Latitude',
             'Longitude']]

     Tracking_ID  Latitude  Longitude
3       TRK-9003  125.0000  -220.0000
9      TRK-10005  115.6702  -233.9471
11     TRK-10006  153.5272  -205.1794
31     TRK-10009  132.4399  -189.5432
109    TRK-10024  141.8426  -217.9205
...          ...       ...        ...
9813   TRK-11879  130.4182  -187.7532
9821   TRK-11881   98.1660  -193.6665
9909   TRK-11897  139.8264  -212.5755
9927   TRK-11901  105.5919  -231.1437
9929   TRK-11902  143.7179  -230.9319

[370 rows x 3 columns]

In [60]:
df['GPS_Status'] = 'VALID'

In [61]:
df.loc[
    (df['Latitude'] < -90) |
    (df['Latitude'] > 90) |
    (df['Longitude'] < -180) |
    (df['Longitude'] > 180),
    'GPS_Status'
] = 'INVALID'

In [62]:
df[['Tracking_ID',
    'Latitude',
    'Longitude',
    'GPS_Status']].head(20)

   Tracking_ID  Latitude  Longitude GPS_Status
0     TRK-9001   20.2961    85.8245      VALID
2     TRK-9002   20.4625    85.8830      VALID
3     TRK-9003  125.0000  -220.0000    INVALID
4     TRK-9002   20.2700    85.8400      VALID
5    TRK-10005   21.0514    86.4668      VALID
6    TRK-10005   21.0596    86.5235      VALID
7    TRK-10005   21.0353    86.5176      VALID
8    TRK-10005   21.0820    86.4943      VALID
9    TRK-10005  115.6702  -233.9471    INVALID
10   TRK-10005   21.0649    86.4960      VALID
11   TRK-10006  153.5272  -205.1794    INVALID
12   TRK-10006   20.4716    85.8665      VALID
13   TRK-10006   20.4442    85.8963      VALID
14   TRK-10006   20.4562    85.9037      VALID
15   TRK-10006   20.4563    85.8560      VALID
17   TRK-10007   19.8202    85.8264      VALID
18   TRK-10007   19.7844    85.8572      VALID
19   TRK-10007   19.8061    85.8035      VALID
20   TRK-10007   19.8058    85.8478      VALID
21   TRK-10007   19.8131    85.8062      VALID

In [63]:
df.to_csv("cleaned_logistics_checkpoint_TC06.csv", index=False)

For testcase-07

In [64]:
df['Event_TS'] = pd.to_datetime(df['Event_TS'], errors='coerce')

In [65]:
df = df.sort_values(by=['Tracking_ID', 'Event_TS'])

In [66]:
pickup = df[df['Event_Code'] == 'PICKUP'][['Tracking_ID', 'Event_TS']]
pickup = pickup.rename(columns={'Event_TS': 'Pickup_Time'})

delivery = df[df['Event_Code'] == 'DELIVERED'][['Tracking_ID', 'Event_TS']]
delivery = delivery.rename(columns={'Event_TS': 'Delivery_Time'})

In [67]:
merged = pd.merge(pickup, delivery, on='Tracking_ID', how='inner')

In [68]:
invalid_order = merged[
    merged['Delivery_Time'] < merged['Pickup_Time']
]

In [69]:
invalid_order.head()

Empty DataFrame
Columns: [Tracking_ID, Pickup_Time, Delivery_Time]
Index: []

In [70]:
print(invalid_order)

Empty DataFrame
Columns: [Tracking_ID, Pickup_Time, Delivery_Time]
Index: []

In [71]:
print("Invalid Event Order:", len(invalid_order))

Invalid Event Order: 0

In [72]:
merged['Event_Order_Status'] = 'VALID'

merged.loc[
    merged['Delivery_Time'] < merged['Pickup_Time'],
    'Event_Order_Status'
] = 'INVESTIGATE'

In [73]:
print(
    merged[['Tracking_ID',
            'Pickup_Time',
            'Delivery_Time',
            'Event_Order_Status']]
)

Empty DataFrame
Columns: [Tracking_ID, Pickup_Time, Delivery_Time, Event_Order_Status]
Index: []

In [74]:
df['Event_Code'] = (
    df['Event_Code']
    .str.upper()
    .str.strip()
    .str.replace(" ", "_")
)

In [75]:
print(df['Event_Code'].unique())

<StringArray>
[         'CREATED',        'PICKED_UP', 'OUT_FOR_DELIVERY',
        'EXCEPTION',         'RETURNED',   'ARRIVED_AT_HUB',
  'LABEL_GENERATED',       'IN_TRANSIT',        'DELIVERED',
    'ORDER_CREATED',    'DELIV_SUCCESS',  'DELIVERY_FAILED',
              'OFD',             'HOLD',              'RTS',
 'RETURN_TO_SENDER']
Length: 16, dtype: str

In [76]:
pickup = df[df['Event_Code'].isin(['PICKUP', 'PICKED_UP'])][['Tracking_ID', 'Event_TS']]
pickup = pickup.rename(columns={'Event_TS_UTC': 'Pickup_Time'})

delivery = df[df['Event_Code'].isin(['DELIVERED', 'DELIV_SUCCESS'])][['Tracking_ID', 'Event_TS']]
delivery = delivery.rename(columns={'Event_TS_UTC': 'Delivery_Time'})

For testcase-08

In [ ]:
#Check All Carrier Names

print(df['Carrier'].unique())

<StringArray>
[       'BLUE JET',        'FASTSHIP',         'BlueJet',           'ROADX',
          'ROAD_X',  'ODISHA EXPRESS',        'Blue-Jet',      'Odisha-Exp',
       'Fast-Ship',   'OdishaExpress', 'roadx_logistics',    'fastship_exp']
Length: 12, dtype: str

In [ ]:
#Count Each Carrier Name

print(df['Carrier'].value_counts())

Carrier
FASTSHIP           1298
ROADX              1289
Blue-Jet            735
ROAD_X              724
Odisha-Exp          717
BlueJet             716
BLUE JET            693
OdishaExpress       681
roadx_logistics     669
Fast-Ship           657
fastship_exp        654
ODISHA EXPRESS      602
Name: count, dtype: int64

In [ ]:
#Remove Extra Spaces

df['Carrier'] = df['Carrier'].str.strip()

In [ ]:
#Convert All Names to Uppercase

df['Carrier'] = df['Carrier'].str.upper()

In [ ]:

print(df['Carrier'].unique())

<StringArray>
[       'BLUE JET',        'FASTSHIP',         'BLUEJET',           'ROADX',
          'ROAD_X',  'ODISHA EXPRESS',        'BLUE-JET',      'ODISHA-EXP',
       'FAST-SHIP',   'ODISHAEXPRESS', 'ROADX_LOGISTICS',    'FASTSHIP_EXP']
Length: 12, dtype: str

In [ ]:
#Create a Mapping Dictionary

carrier_mapping = {
    'FAST-SHIP': 'FASTSHIP',
    'FASTSHIP_EXP': 'FASTSHIP',
    'FASTSHIP': 'FASTSHIP',

    'ROAD_X': 'ROADX',
    'ROADX_LOGISTICS': 'ROADX',
    'ROADX': 'ROADX',

    'BLUE JET': 'BLUEJET',
    'BLUE-JET': 'BLUEJET',
    'BLUEJET': 'BLUEJET',

    'ODISHAEXPRESS': 'ODISHA EXPRESS',
    'ODISHA-EXP': 'ODISHA EXPRESS',
    'ODISHA EXPRESS': 'ODISHA EXPRESS'
}

In [ ]:
#Apply the Mapping

df['Carrier'] = df['Carrier'].replace(carrier_mapping)

In [ ]:
#Verify the Result

print(df['Carrier'].unique())

<StringArray>
['BLUEJET', 'FASTSHIP', 'ROADX', 'ODISHA EXPRESS']
Length: 4, dtype: str

In [84]:
print(df['Carrier'].value_counts())

Carrier
ROADX             2682
FASTSHIP          2609
BLUEJET           2144
ODISHA EXPRESS    2000
Name: count, dtype: int64

In [85]:
print(df[df['Carrier'].isna()])

Empty DataFrame
Columns: [Shipment_ID, Parent_Shipment_ID, Order_Status, Tracking_ID, Parcel_ID, Parcel_Count, Carrier, Service_Level, Scan_Source, Event_TS, Promised_Delivery_TS, Event_Code, Status, Origin_Depot, Destination_Zone, Country_Code, Route_ID, Stop_Seq, GPS_Coords, Weight, Weight_Unit, Dimensions_L_W_H, Dim_Unit, Attempt_No, POD_ID, Exception_Reason, Declared_Value, Freight_Cost, Surcharge, COD_Amount, Claim_Amount, Currency, Customer_Name, Customer_Phone, Street_Address, Weight_kg, Event_Key, Event_TS_UTC, Timezone_Status, Weight_Status, Latitude, Longitude, GPS_Status]
Index: []

[0 rows x 43 columns]

In [86]:
df.to_csv("cleaned_logistics_checkpoint_TC08.csv", index=False)

For testcase-09

In [ ]:
#View Status Values

print(df['Order_Status'].unique())

<StringArray>
['ACTIVE', 'RETURN_RTS', 'VOIDED', 'CANCELLED', 'TEST_ORDER']
Length: 5, dtype: str

In [ ]:
#Keep Only Active Shipments

active_shipments = df[df['Order_Status'] == 'ACTIVE']

In [ ]:
#Check Number of Active Shipments
print(len(active_shipments))

8823

In [ ]:
#Find Duplicate Tracking IDs

duplicate_tracking = active_shipments[
    active_shipments.duplicated(
        subset='Tracking_ID',
        keep=False
    )
]

In [ ]:
#Count Duplicate Records

print("Duplicate Tracking IDs :", len(duplicate_tracking))

Duplicate Tracking IDs : 8820

In [ ]:
#Display Duplicate Records

print(
    duplicate_tracking[
        ['Shipment_ID',
         'Tracking_ID',
         'Order_Status']
    ]
)

     Shipment_ID Tracking_ID Order_Status
5      SHP-10005   TRK-10005       ACTIVE
6      SHP-10005   TRK-10005       ACTIVE
8      SHP-10005   TRK-10005       ACTIVE
9      SHP-10005   TRK-10005       ACTIVE
10     SHP-10005   TRK-10005       ACTIVE
...          ...         ...          ...
9993   SHP-11915   TRK-11915       ACTIVE
9994   SHP-11915   TRK-11915       ACTIVE
9995   SHP-11915   TRK-11915       ACTIVE
9996   SHP-11915   TRK-11915       ACTIVE
9997   SHP-11915   TRK-11915       ACTIVE

[8820 rows x 3 columns]

In [ ]:
#Create Status Column

active_shipments['Tracking_Status'] = 'UNIQUE'

In [ ]:
#Mark Duplicate Records

active_shipments.loc[
    active_shipments.duplicated(
        subset='Tracking_ID',
        keep=False
    ),
    'Tracking_Status'
] = 'DUPLICATE'

In [ ]:
#Display Final Output

print(
    active_shipments[
        ['Shipment_ID',
         'Tracking_ID',
         'Tracking_Status']
    ]
)

     Shipment_ID Tracking_ID Tracking_Status
5      SHP-10005   TRK-10005       DUPLICATE
6      SHP-10005   TRK-10005       DUPLICATE
8      SHP-10005   TRK-10005       DUPLICATE
9      SHP-10005   TRK-10005       DUPLICATE
10     SHP-10005   TRK-10005       DUPLICATE
...          ...         ...             ...
9996   SHP-11915   TRK-11915       DUPLICATE
9997   SHP-11915   TRK-11915       DUPLICATE
0      SHP-10001    TRK-9001          UNIQUE
2      SHP-10002    TRK-9002          UNIQUE
3      SHP-10003    TRK-9003          UNIQUE

[8823 rows x 3 columns]

In [ ]:
#Count Unique and Duplicate

print(active_shipments['Tracking_Status'].value_counts())

Tracking_Status
DUPLICATE    8820
UNIQUE          3
Name: count, dtype: int64

In [ ]:

active_shipments.to_csv(
    "TC09_Duplicate_Tracking.csv",
    index=False
)

In [98]:
print(len(duplicate_tracking))

8820

In [99]:
print(duplicate_tracking['Order_Status'].unique())

<StringArray>
['ACTIVE']
Length: 1, dtype: str

In [100]:
duplicate_tracking['Tracking_ID'].value_counts().head(10)

Tracking_ID
TRK-10900    11
TRK-11034    11
TRK-11643    11
TRK-11729    11
TRK-10020    10
TRK-10037    10
TRK-10168    10
TRK-10305    10
TRK-10580    10
TRK-10680    10
Name: count, dtype: int64

For testcase-10

In [ ]:
#Convert Timestamp Columns

df['Event_TS_UTC'] = pd.to_datetime(df['Event_TS_UTC'])

df['Promised_Delivery_TS'] = pd.to_datetime(df['Promised_Delivery_TS'])

In [ ]:
#Check Event Names

print(df['Event_Code'].unique())

<StringArray>
[         'CREATED',        'PICKED_UP', 'OUT_FOR_DELIVERY',
        'EXCEPTION',         'RETURNED',   'ARRIVED_AT_HUB',
  'LABEL_GENERATED',       'IN_TRANSIT',        'DELIVERED',
    'ORDER_CREATED',    'DELIV_SUCCESS',  'DELIVERY_FAILED',
              'OFD',             'HOLD',              'RTS',
 'RETURN_TO_SENDER']
Length: 16, dtype: str

In [ ]:
#Standardize Event_Code

df['Event_Code'] = (
    df['Event_Code']
      .str.upper()
      .str.strip()
      .str.replace(" ", "_")
)

In [ ]:
#Keep Only Delivered Shipments

delivered = df[
    df['Event_Code'].isin(
        ['DELIVERED', 'DELIV_SUCCESS']
    )
]

In [ ]:
#Compare Delivery Time with Promised Time

delivered['Delivery_Status'] = 'ON_TIME'

delivered.loc[
    delivered['Event_TS_UTC'] >
    delivered['Promised_Delivery_TS'],
    'Delivery_Status'
] = 'LATE'

In [106]:
print(
    delivered[
        [
            'Tracking_ID',
            'Promised_Delivery_TS',
            'Event_TS_UTC',
            'Delivery_Status'
        ]
    ].head(20)
)

    Tracking_ID      Promised_Delivery_TS              Event_TS_UTC  \
15    TRK-10006 2026-07-12 06:39:00+00:00 2026-07-10 22:58:00+00:00
21    TRK-10007 2026-07-28 04:25:00+00:00 2026-07-29 02:26:00+00:00
26    TRK-10008 2026-07-26 01:16:00+00:00 2026-07-25 06:13:00+00:00
31    TRK-10009 2026-07-06 09:09:00+00:00 2026-07-07 04:00:00+00:00
41    TRK-10011                       NaT 2026-07-12 00:09:00+00:00
47    TRK-10012 2026-07-30 19:01:00+00:00 2026-07-30 11:18:00+00:00
52    TRK-10013 2026-07-16 15:42:00+00:00 2026-07-16 13:18:00+00:00
58    TRK-10014 2026-07-04 11:46:00+00:00 2026-07-03 22:35:00+00:00
63    TRK-10015 2026-07-23 03:11:00+00:00 2026-07-22 16:22:00+00:00
68    TRK-10016 2026-07-15 14:02:00+00:00 2026-07-14 09:02:00+00:00
73    TRK-10017 2026-07-20 21:11:00+00:00 2026-07-19 15:35:00+00:00
85    TRK-10019 2026-07-16 19:56:00+00:00 2026-07-16 17:02:00+00:00
137   TRK-10020 2026-07-18 00:35:00+00:00 2026-07-18 04:12:00+00:00
91    TRK-10020 2026-07-28 12:21:00+00:00 2026-07-27 08:28:00+00:00
96    TRK-10021 2026-07-31 06:07:00+00:00 2026-07-30 19:28:00+00:00
123   TRK-10022 2026-07-20 09:00:00+00:00 2026-07-19 21:17:00+00:00
102   TRK-10022 2026-07-28 02:50:00+00:00 2026-07-27 10:35:00+00:00
108   TRK-10023 2026-07-17 03:52:00+00:00 2026-07-15 23:45:00+00:00
113   TRK-10024 2026-07-21 03:30:00+00:00 2026-07-22 23:47:00+00:00
118   TRK-10025 2026-07-15 21:15:00+00:00 2026-07-14 00:27:00+00:00

    Delivery_Status
15          ON_TIME
21             LATE
26          ON_TIME
31             LATE
41          ON_TIME
47          ON_TIME
52          ON_TIME
58          ON_TIME
63          ON_TIME
68          ON_TIME
73          ON_TIME
85          ON_TIME
137            LATE
91          ON_TIME
96          ON_TIME
123         ON_TIME
102         ON_TIME
108         ON_TIME
113            LATE
118         ON_TIME

In [110]:
print(delivered.columns)

Index(['Shipment_ID', 'Parent_Shipment_ID', 'Order_Status', 'Tracking_ID',
       'Parcel_ID', 'Parcel_Count', 'Carrier', 'Service_Level', 'Scan_Source',
       'Event_TS', 'Promised_Delivery_TS', 'Event_Code', 'Status',
       'Origin_Depot', 'Destination_Zone', 'Country_Code', 'Route_ID',
       'Stop_Seq', 'GPS_Coords', 'Weight', 'Weight_Unit', 'Dimensions_L_W_H',
       'Dim_Unit', 'Attempt_No', 'POD_ID', 'Exception_Reason',
       'Declared_Value', 'Freight_Cost', 'Surcharge', 'COD_Amount',
       'Claim_Amount', 'Currency', 'Customer_Name', 'Customer_Phone',
       'Street_Address', 'Weight_kg', 'Event_Key', 'Event_TS_UTC',
       'Timezone_Status', 'Weight_Status', 'Latitude', 'Longitude',
       'GPS_Status', 'Delivery_Status'],
      dtype='str')

In [ ]:
#Count ON_TIME and LATE Shipments

print(
    delivered['Delivery_Status']
    .value_counts()
)

Delivery_Status
ON_TIME    862
LATE       847
Name: count, dtype: int64

In [113]:
#Display Only Late Shipments

print(
    delivered[
        [
            'Tracking_ID',
            'Promised_Delivery_TS',
            'Event_TS_UTC',
            'Delivery_Status'
        ]
    ].head(10)
)

   Tracking_ID      Promised_Delivery_TS              Event_TS_UTC  \
15   TRK-10006 2026-07-12 06:39:00+00:00 2026-07-10 22:58:00+00:00
21   TRK-10007 2026-07-28 04:25:00+00:00 2026-07-29 02:26:00+00:00
26   TRK-10008 2026-07-26 01:16:00+00:00 2026-07-25 06:13:00+00:00
31   TRK-10009 2026-07-06 09:09:00+00:00 2026-07-07 04:00:00+00:00
41   TRK-10011                       NaT 2026-07-12 00:09:00+00:00
47   TRK-10012 2026-07-30 19:01:00+00:00 2026-07-30 11:18:00+00:00
52   TRK-10013 2026-07-16 15:42:00+00:00 2026-07-16 13:18:00+00:00
58   TRK-10014 2026-07-04 11:46:00+00:00 2026-07-03 22:35:00+00:00
63   TRK-10015 2026-07-23 03:11:00+00:00 2026-07-22 16:22:00+00:00
68   TRK-10016 2026-07-15 14:02:00+00:00 2026-07-14 09:02:00+00:00

   Delivery_Status
15         ON_TIME
21            LATE
26         ON_TIME
31            LATE
41         ON_TIME
47         ON_TIME
52         ON_TIME
58         ON_TIME
63         ON_TIME
68         ON_TIME

In [109]:
delivered.to_csv(
    "TC10_Delivery_Promise.csv",
    index=False
)